# Generated by Django 2.1.2 on 2019-03-12 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_review_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='photo',
        ),
        migrations.AddField(
            model_name='review',
            name='review_photo',
            field=models.ImageField(blank=True, null=True, upload_to='review_photo'),
        ),
    ]
