# Generated by Django 2.1.2 on 2019-03-12 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_auto_20190312_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='review_photo',
        ),
    ]
